export { default as Dashboard } from './Dashboard';
export { default as Home } from './Home';
export { default as NotFound } from './NotFound';
export { default as Tour } from './Tour';
export { default as UserList } from './UserList';
export { default as Product } from './Product';
export { default as Account } from './Account';
export { default as Setting } from './Setting';
export { default as Typography } from './Typography';